CREATE TABLE `User_info` (
`user_id` INTEGER PRIMARY KEY AUTO_INCREMENT,
`firstname` VARCHAR(255) NOT NULL,
`lastname` VARCHAR(255) NOT NULL,
`role_id` VARCHAR(255) NULL
);

CREATE TABLE `User_login` (
`login_id` INTEGER PRIMARY KEY AUTO_INCREMENT,
`email` VARCHAR(100) UNIQUE NOT NULL,
`passwordhash` VARCHAR(255) NOT NULL,
`passwordsalt` VARCHAR(255) NOT NULL,
`user_id` INTEGER
);

CREATE TABLE `priviledge` (
`priviledge_id` INTEGER PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE `role` (
`role_id` INTEGER PRIMARY KEY AUTO_INCREMENT,
`name` VARCHAR(255) NOT NULL
);

CREATE TABLE `role_priviledge` (
`id` INTEGER PRIMARY KEY AUTO_INCREMENT,
`role_id` VARCHAR(255) NOT NULL,
`priviledge_id` VARCHAR(255) NOT NULL
)
